### ISSUE TITLE
第3回: Flexbox と Grid について学習する

### ISSUE THREAD

**Issue by mryhryki** [tommykw/css-tutorials#24]

**Comment by mryhryki** [comment]
Flexbox の資料は自分的にはこちらがおすすめです！
https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by hyiromori** [comment]
通知テスト

**Comment by tommykw** [comment]
Flexbox 作ってみました！
https://tommykw.github.io/css-tutorials/css-flexbox/css-flexbox1.html
https://tommykw.github.io/css-tutorials/css-flexbox/css-flexbox2.html
https://tommykw.github.io/css-tutorials/css-flexbox/css-flexbox3.html
https://tommykw.github.io/css-tutorials/css-flexbox/css-flexbox4.html

PR
https://github.com/tommykw/css-tutorials/pull/30

**Comment by tommykw** [comment]
Grid 使ってみました！
https://tommykw.github.io/css-tutorials/css-grid/css-grid1.html
https://tommykw.github.io/css-tutorials/css-grid/css-grid2.html
https://tommykw.github.io/css-tutorials/css-grid/css-grid13html

PR
https://github.com/tommykw/css-tutorials/pull/31

**Comment by mryhryki** [comment]
個人的な意見としては、

- Flexbox: 部分的なレイアウト
- Grid: 全体的なレイアウト

みたいなイメージですね。

Flexbox も万能ではないので、あまり多様しすぎると痛い目を見ます（見ました）

**Comment by mryhryki** [comment]
こちらは終わったのでクローズしますね！
