### ISSUE TITLE
第4回: ブログを作る

### ISSUE THREAD

**Issue by tommykw** [tommykw/css-tutorials#32]
こんな感じです。https://joshwcomeau.com/

**Comment by tommykw** [comment]
わかんなくなったら、Issueとかslackとか

**Comment by mryhryki** [comment]
- Flexbox や Grid も試せると良さそう
- 疑問点とかは Issue に書いていったほうが、経験が蓄積されて良いかも？

**Comment by tommykw** [comment]
https://joshwcomeau.com/
これを作ってみようとしたけど、全然程遠い。。。

https://tommykw.github.io/css-tutorials/

全体の組み方がわかっていない。
<img width="1060" alt="スクリーンショット 2020-11-16 21 50 12" src="https://user-images.githubusercontent.com/744059/99254613-f6084380-2855-11eb-934d-2ee43506328d.png">

**Comment by mryhryki** [comment]
今回はどの辺りを学習しますか〜。
どうやろうとして、何が駄目だったかをまとめておいてもらえると、良い学習につながると思います！

**Comment by mryhryki** [comment]
Slack連携テスト

**Comment by mryhryki** [comment]
```html
<body>
  <div style="width: 1000px; margin: 0 auto; background-color: red">
    <p>Description</p>
  </div>
</body>
```

**Comment by mryhryki** [comment]
[grid-template-areas - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/grid-template-areas)

**Comment by tommykw** [comment]
https://github.com/tommykw/css-tutorials/pull/38
stickyを使った。

引き続き、スタイリングの枠を作る

**Comment by tommykw** [comment]
Gridを入れてみた。
https://github.com/tommykw/css-tutorials/pull/39

![スクリーンショット 2020-11-17 13 27 26](https://user-images.githubusercontent.com/744059/99346723-aae34480-28d8-11eb-8a55-4a66dd0bc6be.png)

先にヘッダーを整える。

**Comment by tommykw** [comment]
stickyを途中で消したい（スクロールすると）
https://connehito.slack.com/archives/C01CQEEQQGN/p1605588006002900

**Comment by mryhryki** [comment]
- z-index を使って、`sticky` の要素の上に別の要素をかぶせる
- JS でスクロール位置がある一定を超えたら消す、みたいな処理を実装する

ぐらいですかねー。

**Comment by tommykw** [comment]
ちょっと書いた。
差分をみてフワッと表示切替しないとだ。
```js
document.addEventListener('scroll', function(e) {
    const myNav = document.getElementById("myNav")

    if (window.scrollY > 100) {
        myNav.style.visibility = "hidden"
        myNav.style.opacity = 0
    } else {
        myNav.style.visibility = "visible"
        myNav.style.opacity = 1
    }
 })
```

**Comment by mryhryki** [comment]
フワッとやるなら、CSS のアニメーションとかですかねー。
そのまま動くかはわからないですけど、以下のスタイルを定義して `#myNav` の要素に `.hidden` クラスを追加したらフワッと消えるようになりそう。

```css
@keyframes fadeout {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}

#myNav.hidden {
  animation: fadeout 0.5s linear;
}
```

**Comment by tommykw** [comment]
`@keyframes` 📝 📝 
ちょっと動きました！Navをきれいにしていこう
![test1](https://user-images.githubusercontent.com/744059/100398047-3eaed080-3090-11eb-813e-9590d66a274a.gif)

**Comment by tommykw** [comment]
@hyiromori 
<img width="847" alt="スクリーンショット 2020-11-30 9 04 37" src="https://user-images.githubusercontent.com/744059/100557255-34d4d980-32eb-11eb-98df-dc781a94e5be.png">

赤枠の余白を消したいのですが、どうすれば良いです？

横のマージンは、

```
body {
    background: #E6E6E6;
    margin: 0;
}
```

body に margin: 0 指定しました。user agent stylesheet っていうのがあるんですね 📝

**Comment by mryhryki** [comment]
（PR でやり取りしたほうがやりやすそう）

**Comment by mryhryki** [comment]
@tommykw 
`ul` 要素にも標準のマージンが設定されているので、それが原因だと思いますね〜。
`ul` にも `margin: 0` を適用すればなくなると思います。
無理に `ul` を使う必要はない場所のような気もしますが。

**Comment by yanamura** [comment]
自分がやるときは最初にcss resetはなにかいれちゃいますね
https://coliss.com/articles/build-websites/operation/css/css-reset-for-modern-browser.html
