### ISSUE TITLE
静的サイトジェネレーターについて調べてみる

### ISSUE THREAD

**Issue by mryhryki** [tommykw/css-tutorials#48]
- [Next.js](https://nextjs.org/)
- [Gatsby.js](https://www.gatsbyjs.com/)
- [Jekyll](http://jekyllrb-ja.github.io/) (GitHub Pages にデフォルトで入っている)
- （他にも色々ありますが、とりあえずこの辺りで）

**Comment by mryhryki** [comment]
よくまとまっていた。

Next.js と Gatsby の比較
https://gotohayato.com/content/511/

> 「かぎられた範囲での効率の高さ」と「汎用性の高さ」はしばしばトレードオフの関係にありますが、その点でいえば Gatsby は「かぎられた範囲での効率の高さ」を、 Next.js は「汎用性の高さ」を優先している印象です。その意味でたとえるなら Gatsby は CMS に、 Next.js はウェブアプリケーションフレームワークに似ていると言えます。このたとえはピンと来ない人には伝わらないと思いますが、伝わる人には伝わると思います。

これ分かりやすい。
個人的には、色々な用途に使える Next.js の方が好き。

**Comment by mryhryki** [comment]
Next.js を調べていたメモ。
初心者の人が順番に書いてるので分かりやすそう。

https://zenn.dev/tiwu_dev/scraps/fbbb0e4342ca5805986a

**Comment by tommykw** [comment]
>  Gatsby の方が個性が強く狭い範囲で強烈な強みを発揮するイメージです

Next.js は汎用性高いんすね。GraphQL 触ってみたいんですよね...Gatsby も捨てがたい。
今回 GraphQL 触る機会なさそうなので Next.js でよさそう。

**Comment by mryhryki** [comment]
もし単にGraphQLを使ってみたい、っていう話であれば、GitHub が API を GraphQL で提供していますね。
オンラインで試すことができるようにもなっているので、どんなものかを知りたいのであればこれを使ってみるのも良いと思います。
https://developer.github.com/v4/explorer/

リポジトリ最大100件とIssue/PRを5件ずつとってくるサンプルです。

```graphql
{
  user(login: "tommykw") {
    name
    repositories(first: 100) {
      nodes {
        name
        url
        issues(first: 5, states: OPEN) {
          nodes {
            title
            createdAt
          }
        }
        pullRequests(first: 5, states: OPEN) {
          nodes {
            title
            createdAt
          }
        }
      }
    }
  }
}
```

**Comment by mryhryki** [comment]
最近のブログを見てても `Next.js` の記事が多そうだから、 `Next.js` で良さそうかな。
（Gatsby.js がある程度成熟したのもあるのかもしれない。Next.js の SSG は割と最近推されているっぽいし）

**Comment by mryhryki** [comment]
`Next.js` でやることに決まったのでクローズ。
